### ISSUE TITLE
I can't get the parallel processing scripts to work

### ISSUE THREAD

**Issue by EwonRael** [indestructible-type/MFEK-Sans#2]
@ctrlcctrlv with so many styles I agree parallel processing is super useful, but I can't seem to run the new scripts.

`GENERATING TTF`
.
`**** Processing: data:,<empty/> ****`
`build-ttf.sh: line 41: parallel: command not found`

`./build-otf.sh: line 66: unexpected EOF while looking for matching `"'`

these are the errors I get when I try and run the new build scripts. I am (as always) not very good with the computers, so it is more than likely that I'm doing something wrong here.

**Comment by ctrlcctrlv** [comment]
depending on your OS , the package should just be called `parallel`

sorry i did not see this before i posted in #1 : 

> let me know by the way if the build system changes cause any issues
> 
> i think you use arch (or manjaro?)
> 
> on either system the needed packages are:
> 
> * `aur/xidel`
> * `extra/parallel`

**Comment by ctrlcctrlv** [comment]
alternatively these are .tar.gz containing both

[parallel.tar.gz](https://github.com/indestructible-type/MFEK-Sans/files/11952737/parallel.tar.gz) (requires Perl be installed but most GNU/Linux distros have it already)
[xidel.tar.gz](https://github.com/indestructible-type/MFEK-Sans/files/11952738/xidel.tar.gz) (completely static binary)

```
[fred@デブ.狸.agency ~/Workspace]$ for f in /tmp/{parallel,xidel}.tar.gz; do tar tf $f; done
usr/bin/parallel
usr/bin/xidel
```

**Comment by EwonRael** [comment]
funny I looked for a "parallel" package and nothing came up but I must have spelled it wrong or something because when I looked again it installed just fine.

OTF script still doesn't work for me... 

`      build-otf.sh: line 66: unexpected EOF while looking for matching '"'`

and TTF script only builds nine fonts (the source fonts no interpolation)

I added a "requirements.txt" because I saw that it requires xidel now, we can throw parallel into there :+1:

**Comment by ctrlcctrlv** [comment]
aha. i had the dev/nightly build of xidel but distributed u `xidel-bin` which i now maintain on AUR. i will send a PR to use a command which works on stable xidel
